
services:
  nginx:
    build: .
    container_name: my-local-nginx
    ports:
      - "80:80"      # HTTP (вирт. хост 1)
      - "443:443"    # HTTPS (вирт. хост 1)
      - "8084:8084"  # Второй HTTP сервер (вирт. хост 2)
      - "8081:8081"  # PHP сервер (вирт. хост 3)
    volumes:
      # Монтирование
      - ./site:/var/www/drug.ru
      - ./nginx-config/drug.ru.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - web-network

  php-fpm:
    image: php:8.2-fpm
    container_name: my-local-php
    volumes:
      - ./site:/var/www/drug.ru
    networks:
      - web-network

networks:
  web-network:
    driver: bridge