##
# You should look at the following URL's in order to grasp a solid understanding
# of Nginx configuration files in order to fully unleash the power of Nginx.
# https://www.nginx.com/resources/wiki/start/
# https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/
# https://wiki.debian.org/Nginx/DirectoryStructure
#
# In most cases, administrators will remove this file from sites-enabled/ and
# leave it as reference inside of sites-available where it will continue to be
# updated by the nginx packaging team.
#
# This file will automatically load configuration files provided by other
# applications, such as Drupal or Wordpress. These applications will be made
# available underneath a path with that package name, such as /drupal8.
#
# Please see /usr/share/doc/nginx-doc/examples/ for more detailed examples.
##

# Default server configuration
#
server {
	listen 443 ssl;
	ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;

	server_name drug.ru;

    root /var/www/drug.ru;
	index index.html;

	# 404
	error_page 404 /error_404.html;
	location = /error_404.html {
    	root /var/www/drug.ru/html;
    	internal;
	}

	# Точное совпадение для корня (самый высокий приоритет)
	location = / {
		root /var/www/drug.ru;
		try_files /index.html =404;
	}

	# Точное совпадение для /user
	location = /user {
		auth_basic "Restricted";
		auth_basic_user_file /etc/nginx/.htpasswd;
		alias /var/www/drug.ru/html;
		try_files /user.html =404;
	}

	# ПРИОРИТЕТ 1: Статические файлы с расширениями (кроме html/php)
	# Используем ^~, чтобы дать им приоритет над регулярными выражениями
	location ^~ /js/ {
		alias /var/www/drug.ru/js/;
		expires 1d;
		add_header Cache-Control "public, no-transform";
		# Эти заголовки помогут при отладке
		add_header X-Debug-Location "js location hit" always;
		add_header X-Real-Path "/var/www/drug.ru/js/$uri" always;
	}

	location ^~ /image/ {
		alias /var/www/drug.ru/image/;
		expires 1d;
		add_header Cache-Control "public, no-transform";
	}

	location ^~ /docs/ {
		alias /var/www/drug.ru/docs/;
		expires 1d;
		add_header Cache-Control "public, no-transform";
	}

	# ПРИОРИТЕТ 2: Регулярные выражения для файлов по расширениям
	# Эти будут проверяться, если не сработали ^~ location'ы выше
	location ~* \.(css)$ {
		# Файл style.css лежит в корне, а не в папке css
		try_files /style.css =404;
		expires 1d;
		add_header Cache-Control "public, no-transform";
	}

	location ~* \.(jpg|jpeg|png|gif|avif)$ {
		# Для изображений используем корень /image
		root /var/www/drug.ru/image;
		expires 1d;
		add_header Cache-Control "public, no-transform";
	}

	location ~* \.(pdf|doc|docx)$ {
		root /var/www/drug.ru/docs;
		expires 1d;
		add_header Cache-Control "public, no-transform";
	}

	# ПРИОРИТЕТ 3: HTML и PHP страницы (самое широкое правило - в конце)
	location ~* ([^\.]*)\.(html)$ {
		alias /var/www/drug.ru/html;
		try_files $1.html =404; 
		expires 1d;
	}

	location ~* ([^\.]*)\.(php)$ {
		alias /var/www/drug.ru/html/php/;
		fastcgi_pass 127.0.0.1:9000;
		include /etc/nginx/fastcgi.conf;
		try_files $1.php =404; 
		expires 1d;
	}

	# Если ничего не подошло - 404
	location / {
		return 404;
	}
}





	# Note: You should disable gzip for SSL traffic.
	# See: https://bugs.debian.org/773332
	#
	# Read up on ssl_ciphers to ensure a secure configuration.
	# See: https://bugs.debian.org/765782
	#
	# Self signed certs generated by the ssl-cert package
	# Don't use them in a production server!
	#
	# include snippets/snakeoil.conf;
	
	#server_name drug.ru www.drug.ru;

	# pass PHP scripts to FastCGI server
	#
	#location ~ \.php$ {
	#	include snippets/fastcgi-php.conf;
	#
	#	# With php-fpm (or other unix sockets):
	#	fastcgi_pass unix:/run/php/php7.4-fpm.sock;
	#	# With php-cgi (or other tcp sockets):
	#	fastcgi_pass 127.0.0.1:9000;
	#}

	# deny access to .htaccess files, if Apache's document root
	# concurs with nginx's one
	#
	#location ~ /\.ht {
	#	deny all;
	#}
 # Virtual Host configuration for example.com
 #
 # You can move that to a different file under sites-available/ and symlink that
 # to sites-enabled/ to enable it.
 #
 server {
 	listen 8084;
 
 	server_name drug.ru;
 
 	root /var/www/drug.ru;
 	index index.html;
 
 	# 404
 	error_page 404 /error_404.html;
 	location = /error_404.html {
     	root /var/www/drug.ru/html;
     	internal;
 	}
 
 	# Точное совпадение для корня (самый высокий приоритет)
 	location = / {
 		root /var/www/drug.ru;
 		try_files /index.html =404;
 	}
 
 	# Точное совпадение для /user
 	location = /user {
 		auth_basic "Restricted";
 		auth_basic_user_file /etc/nginx/.htpasswd;
 		alias /var/www/drug.ru/html;
 		try_files /user.html =404;
 	}
 
 	# ПРИОРИТЕТ 1: Статические файлы с расширениями (кроме html/php)
 	# Используем ^~, чтобы дать им приоритет над регулярными выражениями
 	location ^~ /js/ {
 		alias /var/www/drug.ru/js/;
 		expires 1d;
 		add_header Cache-Control "public, no-transform";
 		# Эти заголовки помогут при отладке
 		add_header X-Debug-Location "js location hit" always;
 		add_header X-Real-Path "/var/www/drug.ru/js/$uri" always;
 	}
 
 	location ^~ /image/ {
 		alias /var/www/drug.ru/image/;
 		expires 1d;
 		add_header Cache-Control "public, no-transform";
 	}
 
 	location ^~ /docs/ {
 		alias /var/www/drug.ru/docs/;
 		expires 1d;
 		add_header Cache-Control "public, no-transform";
 	}
 
 	# ПРИОРИТЕТ 2: Регулярные выражения для файлов по расширениям
 	# Эти будут проверяться, если не сработали ^~ location'ы выше
 	location ~* \.(css)$ {
 		# Файл style.css лежит в корне, а не в папке css
 		try_files /style.css =404;
 		expires 1d;
 		add_header Cache-Control "public, no-transform";
 	}
 
 	location ~* \.(jpg|jpeg|png|gif|avif)$ {
 		# Для изображений используем корень /image
 		root /var/www/drug.ru/image;
 		expires 1d;
 		add_header Cache-Control "public, no-transform";
 	}
 
 	location ~* \.(pdf|doc|docx)$ {
 		root /var/www/drug.ru/docs;
 		expires 1d;
 		add_header Cache-Control "public, no-transform";
 	}
 
 	# ПРИОРИТЕТ 3: HTML и PHP страницы (самое широкое правило - в конце)
 	location ~* ([^\.]*)\.(html|php)$ {
 		alias /var/www/drug.ru/html;
 		try_files $1.html $1.php =404; 
 		expires 1d;
 	}
 
 	# Если ничего не подошло - 404
 	location / {
 		return 404;
 	}
 }
 
# # PORT 80

server {
	listen 8081;

	server_name drug.ru;

	root /var/www/drug.ru;
	index index.php;

	# 404
	error_page 404 /error_404.html;
	location = /error_404.html {
    	root /var/www/drug.ru/html;
    	internal;
	}

	location ~ \.php$ {
		root /var/www/drug.ru;
		fastcgi_pass 127.0.0.1:9000;
		include /etc/nginx/fastcgi.conf;
	}

	location ~ \.php$ {
		alias /var/www/drug.ru/html/php;
		fastcgi_pass 127.0.0.1:9000;
		include /etc/nginx/fastcgi.conf;
	}

#	# Точное совпадение для корня
#	location = / {
#		root /var/www/drug.ru;
#		fastcgi_pass 127.0.0.1:9000;
#		include /etc/nginx/fastcgi.conf;
#	}

#	# ПРИОРИТЕТ 1: Статические файлы с расширениями (кроме html/php)
#	# Используем ^~, чтобы дать им приоритет над регулярными выражениями
#	location ^~ /js/ {
#	alias /var/www/drug.ru/js/;
#		expires 1d;
#		add_header Cache-Control "public, no-transform";
#	location ^~ /js/ {
#	alias /var/www/drug.ru/js/;
#		expires 1d;
#		add_header Cache-Control "public, no-transform";
#		# Эти заголовки помогут при отладке
#		add_header X-Debug-Location "js location hit" always;
#		add_header X-Real-Path "/var/www/drug.ru/js/$uri" always;
#		# Эти заголовки помогут при отладке
#		add_header X-Debug-Location "js location hit" always;
#		add_header X-Real-Path "/var/www/drug.ru/js/$uri" always;
#	}
#
#		# Точное совпадение для /user
#	location = /user {
#		auth_basic "Restricted";
#		auth_basic_user_file /etc/nginx/.htpasswd;
#		alias /var/www/drug.ru/html;
#		try_files /user.html =404;
#	}
#
#	location ^~ /image/ {
#		alias /var/www/drug.ru/image/;
#		expires 1d;
#		add_header Cache-Control "public, no-transform";
#	}
#
#	location ^~ /docs/ {
#		alias /var/www/drug.ru/docs/;
#		expires 1d;
#		add_header Cache-Control "public, no-transform";
#	}
#
#	# ПРИОРИТЕТ 2: Регулярные выражения для файлов по расширениям
#	# Эти будут проверяться, если не сработали ^~ location'ы выше
#	location ~* \.(css)$ {
#		# Файл style.css лежит в корне, а не в папке css
#		try_files /style.css =404;
#		expires 1d;
#		add_header Cache-Control "public, no-transform";
#	}
#
#	location ~* \.(jpg|jpeg|png|gif|avif)$ {
#		# Для изображений используем корень /image
#		root /var/www/drug.ru/image;
#		expires 1d;
#		add_header Cache-Control "public, no-transform";
#	}
#
#	location ~* \.(pdf|doc|docx)$ {
#		root /var/www/drug.ru/docs;
#		expires 1d;
#		add_header Cache-Control "public, no-transform";
#	}
#
#	# ПРИОРИТЕТ 3: HTML и PHP страницы (самое широкое правило - в конце)
#	location ~* ([^\.]*)\.(html)$ {
#		alias /var/www/drug.ru/html;
#		try_files $1.html $1.php =404; 
#		expires 1d;
#	}
#
#	# Если ничего не подошло - 404
#	location / {
#		return 404;
#	}
}
